# Generated by Django 4.0.6 on 2022-08-06 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заявление')),
                ('desc', models.TextField(verbose_name='О компании')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='about_us', verbose_name='Баннер компании')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='about_us', verbose_name='Профиль компании')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(blank=True, null=True, verbose_name='Kartada ýerleşýän ýeriňiz')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Ваша электронная почта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='header_logo', verbose_name='Логотип выше')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='footer_logo', verbose_name='Логотип ниже')),
                ('mini_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание')),
                ('gmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gmail')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mail')),
                ('tiktok', models.CharField(blank=True, max_length=255, null=True, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Эл. адрес')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Мобильный телефон')),
                ('message', models.TextField(verbose_name='SMS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'СМС',
                'verbose_name_plural': 'СМС',
            },
        ),
        migrations.CreateModel(
            name='Galleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleria', verbose_name='Изображение для галереи')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Фотографии для галереи',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider', verbose_name='Слайдер')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.BooleanField(default=False, verbose_name='Акция')),
                ('new', models.BooleanField(default=False, verbose_name='Новый')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Слоган')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Основная фотография')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Вторая фотография')),
                ('three_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Третея фотография')),
                ('packing', models.CharField(blank=True, max_length=255, null=True, verbose_name='Упаковка')),
                ('box_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес коробки')),
                ('quantity_in_the_box', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество в коробке')),
                ('shelf_life', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата истечения срока')),
                ('protein', models.CharField(blank=True, max_length=255, null=True, verbose_name='Белок')),
                ('fat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жир')),
                ('carbohydrate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Углерод')),
                ('the_energy_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение мощности')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_ru.category', verbose_name='Какая категория подходит')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
