# Generated by Django 4.0.6 on 2022-07-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Karopkanyn agramy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Uglerod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fasowka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Belok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_the_box',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Karopkadaky sany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Saklanysh mohleti'),
        ),
        migrations.AlterField(
            model_name='product',
            name='the_energy_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kuwwatlylyk gymmaty'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agramy'),
        ),
    ]
