# Generated by Django 4.0.6 on 2022-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_box_weight_alter_product_carbohydrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gutynyň agramy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gaplamak'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_the_box',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bir gutydaky mukdar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ýaramlylyk möhleti'),
        ),
    ]
