# Generated by Django 4.0.6 on 2022-07-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_box_weight_alter_product_packing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Haysy kategoriya degishliligi'),
        ),
    ]
