# Generated by Django 4.0.6 on 2022-08-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='back_flip_image',
        ),
    ]
