# Generated by Django 4.0.6 on 2022-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Beýan')),
                ('desc', models.TextField(verbose_name='Kompaniýa barada')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us', verbose_name='Kompaniýa barada surat')),
            ],
        ),
        migrations.CreateModel(
            name='Galleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleria', verbose_name='Gallereýa üçin surat')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beýany'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email poçtasy'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='SMS'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='El telefony'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ady'),
        ),
    ]
