# Generated by Django 4.0.6 on 2022-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_about_us_galleria_alter_category_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'Kompaniýa barada', 'verbose_name_plural': 'Kompaniýa barada maglumatlar'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'SMS', 'verbose_name_plural': 'SMSLER'},
        ),
        migrations.AlterModelOptions(
            name='galleria',
            options={'verbose_name': 'Galleria', 'verbose_name_plural': 'Galleria üçin suratlar'},
        ),
        migrations.RenameField(
            model_name='about_us',
            old_name='image',
            new_name='second_image',
        ),
        migrations.AddField(
            model_name='about_us',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us', verbose_name='Kompaniýa barada banner'),
        ),
    ]
