# Generated by Django 4.0.6 on 2022-08-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_about_us_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(verbose_name='Kartada ýerleşýän ýeriňiz')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon belgi')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron poçtaňyz')),
                ('address', models.CharField(max_length=255, verbose_name='Adress')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='header_logo', verbose_name='Ýokardaky logo')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='footer_logo', verbose_name='Aşakdaky logo')),
                ('mini_desc', models.CharField(max_length=255, verbose_name='Gysgaça beýan')),
                ('gmail', models.CharField(max_length=255, verbose_name='Gmail')),
                ('instagram', models.CharField(max_length=255, verbose_name='Instagram')),
                ('mail', models.CharField(max_length=255, verbose_name='Mail')),
                ('tiktok', models.CharField(max_length=255, verbose_name='TikTok')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
            },
        ),
    ]
