# Generated by Django 4.0.6 on 2022-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron poçtaňyz'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='gmail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gmail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='Kartada ýerleşýän ýeriňiz'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mini_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gysgaça beýan'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon belgi'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tiktok',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TikTok'),
        ),
    ]
